use DYNAJS_OPTIONS

diff --git a/dynajs b/dynajs
--- a/dynajs
+++ b/dynajs
@@ -8,20 +8,25 @@ fi
 
 # check if NODE_OPTIONS is set. If it is set, print a warning message
 if [ -n "$NODE_OPTIONS" ]; then
-  echo "Warning: NODE_OPTIONS is set to '$NODE_OPTIONS'. This may cause unexpected behavior." >&2
+  echo "Warning: NODE_OPTIONS is already set to '$NODE_OPTIONS'. Appending to it." >&2
 fi
 
 # check if DYNAJS_HOME is set. If it is not set, print an error message and exit
 if [ -z "$DYNAJS_HOME" ]; then
-  echo "Error: DYNAJS_HOME is not set." >&2
+  echo "Error: DYNAJS_HOME is not set. Please set it to the directory where dynajs is installed." >&2
   exit 1
 fi
 
-# check if DYNAJS_ANALYSIS is set. If it is not set, print a warning message
-if [ -z "$DYNAJS_ANALYSIS" ]; then
-  echo "Warning: DYNAJS_ANALYSIS is not set." >&2
+# check if DYNAJS_OPTIONS is set. If it is not set, print a warning message
+if [ -z "$DYNAJS_OPTIONS" ]; then
+  echo "Warning: DYNAJS_OPTIONS is not set." >&2
 fi
 
-# TODO: check if DYNAJS_PARTIAL_HOOK is set.
+REST="$@"
 
-NODE_OPTIONS="$NODE_OPTIONS --import $DYNAJS_HOME/dist/entry/import.js" "$@"
+# if REST is empty AND DYNAJS_OPTIONS is not set, use `node` to print the help message
+if [ -z "$REST" ] && [ -z "$DYNAJS_OPTIONS" ]; then
+  DYNAJS_OPTIONS="--help" NODE_OPTIONS="$NODE_OPTIONS --import $DYNAJS_HOME/dist/entry/import.js" node
+else
+  NODE_OPTIONS="$NODE_OPTIONS --import $DYNAJS_HOME/dist/entry/import.js" $REST
+fi
